/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "M3AP-IEs"
 * 	found in "../support/r14.1.0/36444-e10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_M3AP_MBMS_Cell_List_H_
#define	_M3AP_MBMS_Cell_List_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct M3AP_ECGI;

/* M3AP_MBMS-Cell-List */
typedef struct M3AP_MBMS_Cell_List {
	A_SEQUENCE_OF(struct M3AP_ECGI) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} M3AP_MBMS_Cell_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_M3AP_MBMS_Cell_List;

#ifdef __cplusplus
}
#endif

#endif	/* _M3AP_MBMS_Cell_List_H_ */
#include <asn_internal.h>
