/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "M3AP-Containers"
 * 	found in "../support/r14.1.0/36444-e10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_M3AP_ProtocolIE_FieldPair_H_
#define	_M3AP_ProtocolIE_FieldPair_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif	/* _M3AP_ProtocolIE_FieldPair_H_ */
#include <asn_internal.h>
