/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "M3AP-PDU-Contents"
 * 	found in "../support/r14.1.0/36444-e10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_M3AP_ResetType_H_
#define	_M3AP_ResetType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "M3AP_ResetAll.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum M3AP_ResetType_PR {
	M3AP_ResetType_PR_NOTHING,	/* No components present */
	M3AP_ResetType_PR_m3_Interface,
	M3AP_ResetType_PR_partOfM3_Interface
	/* Extensions may appear below */
	
} M3AP_ResetType_PR;

/* Forward declarations */
struct M3AP_MBMS_Service_associatedLogicalM3_ConnectionListRes;

/* M3AP_ResetType */
typedef struct M3AP_ResetType {
	M3AP_ResetType_PR present;
	union M3AP_ResetType_u {
		M3AP_ResetAll_t	 m3_Interface;
		struct M3AP_MBMS_Service_associatedLogicalM3_ConnectionListRes	*partOfM3_Interface;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} M3AP_ResetType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_M3AP_ResetType;

#ifdef __cplusplus
}
#endif

#endif	/* _M3AP_ResetType_H_ */
#include <asn_internal.h>
