/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _M3AP_ASN_CONSTANT_H
#define _M3AP_ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define M3AP_maxPrivateIEs (65535)
#define M3AP_maxProtocolExtensions (65535)
#define M3AP_maxProtocolIEs (65535)
#define M3AP_maxnoofMBMSServiceAreaIdentitiesPerMCE (65536)
#define M3AP_maxnooferrors (256)
#define M3AP_maxNrOfIndividualM3ConnectionsToReset (256)
#define M3AP_maxnoofCellsforMBMS (4096)


#ifdef __cplusplus
}
#endif

#endif /* _M3AP_ASN_CONSTANT_H */
