/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "M3AP-PDU-Descriptions"
 * 	found in "../support/r14.1.0/36444-e10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_M3AP_M3AP_PDU_H_
#define	_M3AP_M3AP_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum M3AP_M3AP_PDU_PR {
	M3AP_M3AP_PDU_PR_NOTHING,	/* No components present */
	M3AP_M3AP_PDU_PR_initiatingMessage,
	M3AP_M3AP_PDU_PR_successfulOutcome,
	M3AP_M3AP_PDU_PR_unsuccessfulOutcome
	/* Extensions may appear below */
	
} M3AP_M3AP_PDU_PR;

/* Forward declarations */
struct M3AP_InitiatingMessage;
struct M3AP_SuccessfulOutcome;
struct M3AP_UnsuccessfulOutcome;

/* M3AP_M3AP-PDU */
typedef struct M3AP_M3AP_PDU {
	M3AP_M3AP_PDU_PR present;
	union M3AP_M3AP_PDU_u {
		struct M3AP_InitiatingMessage	*initiatingMessage;
		struct M3AP_SuccessfulOutcome	*successfulOutcome;
		struct M3AP_UnsuccessfulOutcome	*unsuccessfulOutcome;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} M3AP_M3AP_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_M3AP_M3AP_PDU;

#ifdef __cplusplus
}
#endif

#endif	/* _M3AP_M3AP_PDU_H_ */
#include <asn_internal.h>
