/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "M3AP-IEs"
 * 	found in "../support/r14.1.0/36444-e10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_M3AP_CriticalityDiagnostics_H_
#define	_M3AP_CriticalityDiagnostics_H_


#include <asn_application.h>

/* Including external dependencies */
#include "M3AP_ProcedureCode.h"
#include "M3AP_TriggeringMessage.h"
#include "M3AP_Criticality.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct M3AP_CriticalityDiagnostics_IE_List;
struct M3AP_ProtocolExtensionContainer;

/* M3AP_CriticalityDiagnostics */
typedef struct M3AP_CriticalityDiagnostics {
	M3AP_ProcedureCode_t	*procedureCode;	/* OPTIONAL */
	M3AP_TriggeringMessage_t	*triggeringMessage;	/* OPTIONAL */
	M3AP_Criticality_t	*procedureCriticality;	/* OPTIONAL */
	struct M3AP_CriticalityDiagnostics_IE_List	*iEsCriticalityDiagnostics;	/* OPTIONAL */
	struct M3AP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} M3AP_CriticalityDiagnostics_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_M3AP_CriticalityDiagnostics;

#ifdef __cplusplus
}
#endif

#endif	/* _M3AP_CriticalityDiagnostics_H_ */
#include <asn_internal.h>
