/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "M3AP-IEs"
 * 	found in "../support/r14.1.0/36444-e10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_M3AP_TNL_Information_H_
#define	_M3AP_TNL_Information_H_


#include <asn_application.h>

/* Including external dependencies */
#include "M3AP_IPAddress.h"
#include "M3AP_GTP-TEID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct M3AP_ProtocolExtensionContainer;

/* M3AP_TNL-Information */
typedef struct M3AP_TNL_Information {
	M3AP_IPAddress_t	 iPMCAddress;
	M3AP_IPAddress_t	 iPSourceAddress;
	M3AP_GTP_TEID_t	 gTP_DLTEID;
	struct M3AP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} M3AP_TNL_Information_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_M3AP_TNL_Information;

#ifdef __cplusplus
}
#endif

#endif	/* _M3AP_TNL_Information_H_ */
#include <asn_internal.h>
