/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "M3AP-Containers"
 * 	found in "../support/r14.1.0/36444-e10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "M3AP_ProtocolIE-Container.h"

#include "M3AP_ProtocolIE-Field.h"
static asn_oer_constraints_t asn_OER_type_M3AP_ProtocolIE_Container_1238P0_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_M3AP_ProtocolIE_Container_1238P0_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_M3AP_ProtocolIE_Container_1238P1_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_M3AP_ProtocolIE_Container_1238P1_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_M3AP_ProtocolIE_Container_1238P2_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_M3AP_ProtocolIE_Container_1238P2_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_M3AP_ProtocolIE_Container_1238P3_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_M3AP_ProtocolIE_Container_1238P3_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_M3AP_ProtocolIE_Container_1238P4_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_M3AP_ProtocolIE_Container_1238P4_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_M3AP_ProtocolIE_Container_1238P5_constr_11 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_M3AP_ProtocolIE_Container_1238P5_constr_11 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_M3AP_ProtocolIE_Container_1238P6_constr_13 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_M3AP_ProtocolIE_Container_1238P6_constr_13 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_M3AP_ProtocolIE_Container_1238P7_constr_15 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_M3AP_ProtocolIE_Container_1238P7_constr_15 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_M3AP_ProtocolIE_Container_1238P8_constr_17 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_M3AP_ProtocolIE_Container_1238P8_constr_17 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_M3AP_ProtocolIE_Container_1238P9_constr_19 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_M3AP_ProtocolIE_Container_1238P9_constr_19 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_M3AP_ProtocolIE_Container_1238P10_constr_21 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_M3AP_ProtocolIE_Container_1238P10_constr_21 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_M3AP_ProtocolIE_Container_1238P11_constr_23 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_M3AP_ProtocolIE_Container_1238P11_constr_23 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_M3AP_ProtocolIE_Container_1238P12_constr_25 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_M3AP_ProtocolIE_Container_1238P12_constr_25 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_M3AP_ProtocolIE_Container_1238P13_constr_27 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_M3AP_ProtocolIE_Container_1238P13_constr_27 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_M3AP_ProtocolIE_Container_1238P14_constr_29 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_M3AP_ProtocolIE_Container_1238P14_constr_29 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_M3AP_ProtocolIE_Container_1238P15_constr_31 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_M3AP_ProtocolIE_Container_1238P15_constr_31 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_M3AP_ProtocolIE_Container_1238P16_constr_33 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_M3AP_ProtocolIE_Container_1238P16_constr_33 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_M3AP_ProtocolIE_Container_1238P0_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M3AP_MBMSSessionStartRequest_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M3AP_ProtocolIE_Container_1238P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_M3AP_ProtocolIE_Container_1238P0_specs_1 = {
	sizeof(struct M3AP_ProtocolIE_Container_1238P0),
	offsetof(struct M3AP_ProtocolIE_Container_1238P0, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M3AP_ProtocolIE_Container_1238P0 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_M3AP_ProtocolIE_Container_1238P0_tags_1,
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P0_tags_1)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P0_tags_1[0]), /* 1 */
	asn_DEF_M3AP_ProtocolIE_Container_1238P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P0_tags_1)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P0_tags_1[0]), /* 1 */
	{ &asn_OER_type_M3AP_ProtocolIE_Container_1238P0_constr_1, &asn_PER_type_M3AP_ProtocolIE_Container_1238P0_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_M3AP_ProtocolIE_Container_1238P0_1,
	1,	/* Single element */
	&asn_SPC_M3AP_ProtocolIE_Container_1238P0_specs_1	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_M3AP_ProtocolIE_Container_1238P1_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M3AP_MBMSSessionStartResponse_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M3AP_ProtocolIE_Container_1238P1_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_M3AP_ProtocolIE_Container_1238P1_specs_3 = {
	sizeof(struct M3AP_ProtocolIE_Container_1238P1),
	offsetof(struct M3AP_ProtocolIE_Container_1238P1, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M3AP_ProtocolIE_Container_1238P1 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_M3AP_ProtocolIE_Container_1238P1_tags_3,
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P1_tags_3)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P1_tags_3[0]), /* 1 */
	asn_DEF_M3AP_ProtocolIE_Container_1238P1_tags_3,	/* Same as above */
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P1_tags_3)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P1_tags_3[0]), /* 1 */
	{ &asn_OER_type_M3AP_ProtocolIE_Container_1238P1_constr_3, &asn_PER_type_M3AP_ProtocolIE_Container_1238P1_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_M3AP_ProtocolIE_Container_1238P1_3,
	1,	/* Single element */
	&asn_SPC_M3AP_ProtocolIE_Container_1238P1_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_M3AP_ProtocolIE_Container_1238P2_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M3AP_MBMSSessionStartFailure_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M3AP_ProtocolIE_Container_1238P2_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_M3AP_ProtocolIE_Container_1238P2_specs_5 = {
	sizeof(struct M3AP_ProtocolIE_Container_1238P2),
	offsetof(struct M3AP_ProtocolIE_Container_1238P2, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M3AP_ProtocolIE_Container_1238P2 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_M3AP_ProtocolIE_Container_1238P2_tags_5,
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P2_tags_5)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P2_tags_5[0]), /* 1 */
	asn_DEF_M3AP_ProtocolIE_Container_1238P2_tags_5,	/* Same as above */
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P2_tags_5)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P2_tags_5[0]), /* 1 */
	{ &asn_OER_type_M3AP_ProtocolIE_Container_1238P2_constr_5, &asn_PER_type_M3AP_ProtocolIE_Container_1238P2_constr_5, SEQUENCE_OF_constraint },
	asn_MBR_M3AP_ProtocolIE_Container_1238P2_5,
	1,	/* Single element */
	&asn_SPC_M3AP_ProtocolIE_Container_1238P2_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_M3AP_ProtocolIE_Container_1238P3_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M3AP_MBMSSessionStopRequest_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M3AP_ProtocolIE_Container_1238P3_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_M3AP_ProtocolIE_Container_1238P3_specs_7 = {
	sizeof(struct M3AP_ProtocolIE_Container_1238P3),
	offsetof(struct M3AP_ProtocolIE_Container_1238P3, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M3AP_ProtocolIE_Container_1238P3 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_M3AP_ProtocolIE_Container_1238P3_tags_7,
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P3_tags_7)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P3_tags_7[0]), /* 1 */
	asn_DEF_M3AP_ProtocolIE_Container_1238P3_tags_7,	/* Same as above */
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P3_tags_7)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P3_tags_7[0]), /* 1 */
	{ &asn_OER_type_M3AP_ProtocolIE_Container_1238P3_constr_7, &asn_PER_type_M3AP_ProtocolIE_Container_1238P3_constr_7, SEQUENCE_OF_constraint },
	asn_MBR_M3AP_ProtocolIE_Container_1238P3_7,
	1,	/* Single element */
	&asn_SPC_M3AP_ProtocolIE_Container_1238P3_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_M3AP_ProtocolIE_Container_1238P4_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M3AP_MBMSSessionStopResponse_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M3AP_ProtocolIE_Container_1238P4_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_M3AP_ProtocolIE_Container_1238P4_specs_9 = {
	sizeof(struct M3AP_ProtocolIE_Container_1238P4),
	offsetof(struct M3AP_ProtocolIE_Container_1238P4, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M3AP_ProtocolIE_Container_1238P4 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_M3AP_ProtocolIE_Container_1238P4_tags_9,
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P4_tags_9)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P4_tags_9[0]), /* 1 */
	asn_DEF_M3AP_ProtocolIE_Container_1238P4_tags_9,	/* Same as above */
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P4_tags_9)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P4_tags_9[0]), /* 1 */
	{ &asn_OER_type_M3AP_ProtocolIE_Container_1238P4_constr_9, &asn_PER_type_M3AP_ProtocolIE_Container_1238P4_constr_9, SEQUENCE_OF_constraint },
	asn_MBR_M3AP_ProtocolIE_Container_1238P4_9,
	1,	/* Single element */
	&asn_SPC_M3AP_ProtocolIE_Container_1238P4_specs_9	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_M3AP_ProtocolIE_Container_1238P5_11[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M3AP_MBMSSessionUpdateRequest_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M3AP_ProtocolIE_Container_1238P5_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_M3AP_ProtocolIE_Container_1238P5_specs_11 = {
	sizeof(struct M3AP_ProtocolIE_Container_1238P5),
	offsetof(struct M3AP_ProtocolIE_Container_1238P5, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M3AP_ProtocolIE_Container_1238P5 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_M3AP_ProtocolIE_Container_1238P5_tags_11,
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P5_tags_11)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P5_tags_11[0]), /* 1 */
	asn_DEF_M3AP_ProtocolIE_Container_1238P5_tags_11,	/* Same as above */
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P5_tags_11)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P5_tags_11[0]), /* 1 */
	{ &asn_OER_type_M3AP_ProtocolIE_Container_1238P5_constr_11, &asn_PER_type_M3AP_ProtocolIE_Container_1238P5_constr_11, SEQUENCE_OF_constraint },
	asn_MBR_M3AP_ProtocolIE_Container_1238P5_11,
	1,	/* Single element */
	&asn_SPC_M3AP_ProtocolIE_Container_1238P5_specs_11	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_M3AP_ProtocolIE_Container_1238P6_13[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M3AP_MBMSSessionUpdateResponse_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M3AP_ProtocolIE_Container_1238P6_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_M3AP_ProtocolIE_Container_1238P6_specs_13 = {
	sizeof(struct M3AP_ProtocolIE_Container_1238P6),
	offsetof(struct M3AP_ProtocolIE_Container_1238P6, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M3AP_ProtocolIE_Container_1238P6 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_M3AP_ProtocolIE_Container_1238P6_tags_13,
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P6_tags_13)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P6_tags_13[0]), /* 1 */
	asn_DEF_M3AP_ProtocolIE_Container_1238P6_tags_13,	/* Same as above */
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P6_tags_13)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P6_tags_13[0]), /* 1 */
	{ &asn_OER_type_M3AP_ProtocolIE_Container_1238P6_constr_13, &asn_PER_type_M3AP_ProtocolIE_Container_1238P6_constr_13, SEQUENCE_OF_constraint },
	asn_MBR_M3AP_ProtocolIE_Container_1238P6_13,
	1,	/* Single element */
	&asn_SPC_M3AP_ProtocolIE_Container_1238P6_specs_13	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_M3AP_ProtocolIE_Container_1238P7_15[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M3AP_MBMSSessionUpdateFailure_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M3AP_ProtocolIE_Container_1238P7_tags_15[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_M3AP_ProtocolIE_Container_1238P7_specs_15 = {
	sizeof(struct M3AP_ProtocolIE_Container_1238P7),
	offsetof(struct M3AP_ProtocolIE_Container_1238P7, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M3AP_ProtocolIE_Container_1238P7 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_M3AP_ProtocolIE_Container_1238P7_tags_15,
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P7_tags_15)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P7_tags_15[0]), /* 1 */
	asn_DEF_M3AP_ProtocolIE_Container_1238P7_tags_15,	/* Same as above */
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P7_tags_15)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P7_tags_15[0]), /* 1 */
	{ &asn_OER_type_M3AP_ProtocolIE_Container_1238P7_constr_15, &asn_PER_type_M3AP_ProtocolIE_Container_1238P7_constr_15, SEQUENCE_OF_constraint },
	asn_MBR_M3AP_ProtocolIE_Container_1238P7_15,
	1,	/* Single element */
	&asn_SPC_M3AP_ProtocolIE_Container_1238P7_specs_15	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_M3AP_ProtocolIE_Container_1238P8_17[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M3AP_ErrorIndication_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M3AP_ProtocolIE_Container_1238P8_tags_17[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_M3AP_ProtocolIE_Container_1238P8_specs_17 = {
	sizeof(struct M3AP_ProtocolIE_Container_1238P8),
	offsetof(struct M3AP_ProtocolIE_Container_1238P8, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M3AP_ProtocolIE_Container_1238P8 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_M3AP_ProtocolIE_Container_1238P8_tags_17,
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P8_tags_17)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P8_tags_17[0]), /* 1 */
	asn_DEF_M3AP_ProtocolIE_Container_1238P8_tags_17,	/* Same as above */
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P8_tags_17)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P8_tags_17[0]), /* 1 */
	{ &asn_OER_type_M3AP_ProtocolIE_Container_1238P8_constr_17, &asn_PER_type_M3AP_ProtocolIE_Container_1238P8_constr_17, SEQUENCE_OF_constraint },
	asn_MBR_M3AP_ProtocolIE_Container_1238P8_17,
	1,	/* Single element */
	&asn_SPC_M3AP_ProtocolIE_Container_1238P8_specs_17	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_M3AP_ProtocolIE_Container_1238P9_19[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M3AP_ResetIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M3AP_ProtocolIE_Container_1238P9_tags_19[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_M3AP_ProtocolIE_Container_1238P9_specs_19 = {
	sizeof(struct M3AP_ProtocolIE_Container_1238P9),
	offsetof(struct M3AP_ProtocolIE_Container_1238P9, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M3AP_ProtocolIE_Container_1238P9 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_M3AP_ProtocolIE_Container_1238P9_tags_19,
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P9_tags_19)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P9_tags_19[0]), /* 1 */
	asn_DEF_M3AP_ProtocolIE_Container_1238P9_tags_19,	/* Same as above */
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P9_tags_19)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P9_tags_19[0]), /* 1 */
	{ &asn_OER_type_M3AP_ProtocolIE_Container_1238P9_constr_19, &asn_PER_type_M3AP_ProtocolIE_Container_1238P9_constr_19, SEQUENCE_OF_constraint },
	asn_MBR_M3AP_ProtocolIE_Container_1238P9_19,
	1,	/* Single element */
	&asn_SPC_M3AP_ProtocolIE_Container_1238P9_specs_19	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_M3AP_ProtocolIE_Container_1238P10_21[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M3AP_ResetAcknowledgeIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M3AP_ProtocolIE_Container_1238P10_tags_21[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_M3AP_ProtocolIE_Container_1238P10_specs_21 = {
	sizeof(struct M3AP_ProtocolIE_Container_1238P10),
	offsetof(struct M3AP_ProtocolIE_Container_1238P10, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M3AP_ProtocolIE_Container_1238P10 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_M3AP_ProtocolIE_Container_1238P10_tags_21,
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P10_tags_21)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P10_tags_21[0]), /* 1 */
	asn_DEF_M3AP_ProtocolIE_Container_1238P10_tags_21,	/* Same as above */
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P10_tags_21)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P10_tags_21[0]), /* 1 */
	{ &asn_OER_type_M3AP_ProtocolIE_Container_1238P10_constr_21, &asn_PER_type_M3AP_ProtocolIE_Container_1238P10_constr_21, SEQUENCE_OF_constraint },
	asn_MBR_M3AP_ProtocolIE_Container_1238P10_21,
	1,	/* Single element */
	&asn_SPC_M3AP_ProtocolIE_Container_1238P10_specs_21	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_M3AP_ProtocolIE_Container_1238P11_23[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M3AP_M3SetupRequestIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M3AP_ProtocolIE_Container_1238P11_tags_23[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_M3AP_ProtocolIE_Container_1238P11_specs_23 = {
	sizeof(struct M3AP_ProtocolIE_Container_1238P11),
	offsetof(struct M3AP_ProtocolIE_Container_1238P11, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M3AP_ProtocolIE_Container_1238P11 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_M3AP_ProtocolIE_Container_1238P11_tags_23,
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P11_tags_23)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P11_tags_23[0]), /* 1 */
	asn_DEF_M3AP_ProtocolIE_Container_1238P11_tags_23,	/* Same as above */
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P11_tags_23)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P11_tags_23[0]), /* 1 */
	{ &asn_OER_type_M3AP_ProtocolIE_Container_1238P11_constr_23, &asn_PER_type_M3AP_ProtocolIE_Container_1238P11_constr_23, SEQUENCE_OF_constraint },
	asn_MBR_M3AP_ProtocolIE_Container_1238P11_23,
	1,	/* Single element */
	&asn_SPC_M3AP_ProtocolIE_Container_1238P11_specs_23	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_M3AP_ProtocolIE_Container_1238P12_25[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M3AP_M3SetupResponseIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M3AP_ProtocolIE_Container_1238P12_tags_25[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_M3AP_ProtocolIE_Container_1238P12_specs_25 = {
	sizeof(struct M3AP_ProtocolIE_Container_1238P12),
	offsetof(struct M3AP_ProtocolIE_Container_1238P12, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M3AP_ProtocolIE_Container_1238P12 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_M3AP_ProtocolIE_Container_1238P12_tags_25,
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P12_tags_25)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P12_tags_25[0]), /* 1 */
	asn_DEF_M3AP_ProtocolIE_Container_1238P12_tags_25,	/* Same as above */
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P12_tags_25)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P12_tags_25[0]), /* 1 */
	{ &asn_OER_type_M3AP_ProtocolIE_Container_1238P12_constr_25, &asn_PER_type_M3AP_ProtocolIE_Container_1238P12_constr_25, SEQUENCE_OF_constraint },
	asn_MBR_M3AP_ProtocolIE_Container_1238P12_25,
	1,	/* Single element */
	&asn_SPC_M3AP_ProtocolIE_Container_1238P12_specs_25	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_M3AP_ProtocolIE_Container_1238P13_27[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M3AP_M3SetupFailureIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M3AP_ProtocolIE_Container_1238P13_tags_27[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_M3AP_ProtocolIE_Container_1238P13_specs_27 = {
	sizeof(struct M3AP_ProtocolIE_Container_1238P13),
	offsetof(struct M3AP_ProtocolIE_Container_1238P13, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M3AP_ProtocolIE_Container_1238P13 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_M3AP_ProtocolIE_Container_1238P13_tags_27,
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P13_tags_27)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P13_tags_27[0]), /* 1 */
	asn_DEF_M3AP_ProtocolIE_Container_1238P13_tags_27,	/* Same as above */
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P13_tags_27)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P13_tags_27[0]), /* 1 */
	{ &asn_OER_type_M3AP_ProtocolIE_Container_1238P13_constr_27, &asn_PER_type_M3AP_ProtocolIE_Container_1238P13_constr_27, SEQUENCE_OF_constraint },
	asn_MBR_M3AP_ProtocolIE_Container_1238P13_27,
	1,	/* Single element */
	&asn_SPC_M3AP_ProtocolIE_Container_1238P13_specs_27	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_M3AP_ProtocolIE_Container_1238P14_29[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M3AP_MCEConfigurationUpdateIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M3AP_ProtocolIE_Container_1238P14_tags_29[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_M3AP_ProtocolIE_Container_1238P14_specs_29 = {
	sizeof(struct M3AP_ProtocolIE_Container_1238P14),
	offsetof(struct M3AP_ProtocolIE_Container_1238P14, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M3AP_ProtocolIE_Container_1238P14 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_M3AP_ProtocolIE_Container_1238P14_tags_29,
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P14_tags_29)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P14_tags_29[0]), /* 1 */
	asn_DEF_M3AP_ProtocolIE_Container_1238P14_tags_29,	/* Same as above */
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P14_tags_29)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P14_tags_29[0]), /* 1 */
	{ &asn_OER_type_M3AP_ProtocolIE_Container_1238P14_constr_29, &asn_PER_type_M3AP_ProtocolIE_Container_1238P14_constr_29, SEQUENCE_OF_constraint },
	asn_MBR_M3AP_ProtocolIE_Container_1238P14_29,
	1,	/* Single element */
	&asn_SPC_M3AP_ProtocolIE_Container_1238P14_specs_29	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_M3AP_ProtocolIE_Container_1238P15_31[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M3AP_MCEConfigurationUpdateAcknowledgeIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M3AP_ProtocolIE_Container_1238P15_tags_31[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_M3AP_ProtocolIE_Container_1238P15_specs_31 = {
	sizeof(struct M3AP_ProtocolIE_Container_1238P15),
	offsetof(struct M3AP_ProtocolIE_Container_1238P15, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M3AP_ProtocolIE_Container_1238P15 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_M3AP_ProtocolIE_Container_1238P15_tags_31,
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P15_tags_31)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P15_tags_31[0]), /* 1 */
	asn_DEF_M3AP_ProtocolIE_Container_1238P15_tags_31,	/* Same as above */
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P15_tags_31)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P15_tags_31[0]), /* 1 */
	{ &asn_OER_type_M3AP_ProtocolIE_Container_1238P15_constr_31, &asn_PER_type_M3AP_ProtocolIE_Container_1238P15_constr_31, SEQUENCE_OF_constraint },
	asn_MBR_M3AP_ProtocolIE_Container_1238P15_31,
	1,	/* Single element */
	&asn_SPC_M3AP_ProtocolIE_Container_1238P15_specs_31	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_M3AP_ProtocolIE_Container_1238P16_33[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M3AP_MCEConfigurationUpdateFailureIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M3AP_ProtocolIE_Container_1238P16_tags_33[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_M3AP_ProtocolIE_Container_1238P16_specs_33 = {
	sizeof(struct M3AP_ProtocolIE_Container_1238P16),
	offsetof(struct M3AP_ProtocolIE_Container_1238P16, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M3AP_ProtocolIE_Container_1238P16 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_M3AP_ProtocolIE_Container_1238P16_tags_33,
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P16_tags_33)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P16_tags_33[0]), /* 1 */
	asn_DEF_M3AP_ProtocolIE_Container_1238P16_tags_33,	/* Same as above */
	sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P16_tags_33)
		/sizeof(asn_DEF_M3AP_ProtocolIE_Container_1238P16_tags_33[0]), /* 1 */
	{ &asn_OER_type_M3AP_ProtocolIE_Container_1238P16_constr_33, &asn_PER_type_M3AP_ProtocolIE_Container_1238P16_constr_33, SEQUENCE_OF_constraint },
	asn_MBR_M3AP_ProtocolIE_Container_1238P16_33,
	1,	/* Single element */
	&asn_SPC_M3AP_ProtocolIE_Container_1238P16_specs_33	/* Additional specs */
};

