/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_M3AP_PDU;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_InitiatingMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_SuccessfulOutcome;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_UnsuccessfulOutcome;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMSSessionStartRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMSSessionStartResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMSSessionStartFailure;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMSSessionStopRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMSSessionStopResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMSSessionUpdateRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMSSessionUpdateResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMSSessionUpdateFailure;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_ErrorIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_Reset;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_ResetType;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_ResetAll;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMS_Service_associatedLogicalM3_ConnectionListRes;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_ResetAcknowledge;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMS_Service_associatedLogicalM3_ConnectionListResAck;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_PrivateMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_M3SetupRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMSServiceAreaListItem;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_M3SetupResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_M3SetupFailure;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MCEConfigurationUpdate;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MCEConfigurationUpdateAcknowledge;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MCEConfigurationUpdateFailure;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_Absolute_Time_ofMBMS_Data;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_AllocationAndRetentionPriority;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_BitRate;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_Cause;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_CauseMisc;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_CauseNAS;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_CauseProtocol;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_CauseRadioNetwork;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_CauseTransport;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_CriticalityDiagnostics;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_CriticalityDiagnostics_IE_List;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_ECGI;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_EUTRANCellIdentifier;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_ExtendedMCE_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_Global_MCE_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_GBR_QosInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_GTP_TEID;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_IPAddress;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMS_Cell_List;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMS_E_RAB_QoS_Parameters;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMS_Service_associatedLogicalM3_ConnectionItem;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMSServiceArea1;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMS_Service_Area;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMS_Session_Duration;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MBMS_Session_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MCE_MBMS_M3AP_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MCE_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MCEname;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MinimumTimeToMBMSDataTransfer;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_MME_MBMS_M3AP_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_Pre_emptionCapability;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_Pre_emptionVulnerability;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_PriorityLevel;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_PLMN_Identity;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_QCI;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_Reestablishment;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_TimeToWait;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_TMGI;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_TNL_Information;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_TypeOfError;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_Criticality;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_Presence;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_PrivateIE_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_ProcedureCode;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_ProtocolIE_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_M3AP_TriggeringMessage;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module M3AP-PDU-Descriptions in ../support/r14.1.0/36444-e10.asn */
	&asn_DEF_M3AP_M3AP_PDU,	
	&asn_DEF_M3AP_InitiatingMessage,	
	&asn_DEF_M3AP_SuccessfulOutcome,	
	&asn_DEF_M3AP_UnsuccessfulOutcome,	
	/* From module M3AP-PDU-Contents in ../support/r14.1.0/36444-e10.asn */
	&asn_DEF_M3AP_MBMSSessionStartRequest,	
	&asn_DEF_M3AP_MBMSSessionStartResponse,	
	&asn_DEF_M3AP_MBMSSessionStartFailure,	
	&asn_DEF_M3AP_MBMSSessionStopRequest,	
	&asn_DEF_M3AP_MBMSSessionStopResponse,	
	&asn_DEF_M3AP_MBMSSessionUpdateRequest,	
	&asn_DEF_M3AP_MBMSSessionUpdateResponse,	
	&asn_DEF_M3AP_MBMSSessionUpdateFailure,	
	&asn_DEF_M3AP_ErrorIndication,	
	&asn_DEF_M3AP_Reset,	
	&asn_DEF_M3AP_ResetType,	
	&asn_DEF_M3AP_ResetAll,	
	&asn_DEF_M3AP_MBMS_Service_associatedLogicalM3_ConnectionListRes,	
	&asn_DEF_M3AP_ResetAcknowledge,	
	&asn_DEF_M3AP_MBMS_Service_associatedLogicalM3_ConnectionListResAck,	
	&asn_DEF_M3AP_PrivateMessage,	
	&asn_DEF_M3AP_M3SetupRequest,	
	&asn_DEF_M3AP_MBMSServiceAreaListItem,	
	&asn_DEF_M3AP_M3SetupResponse,	
	&asn_DEF_M3AP_M3SetupFailure,	
	&asn_DEF_M3AP_MCEConfigurationUpdate,	
	&asn_DEF_M3AP_MCEConfigurationUpdateAcknowledge,	
	&asn_DEF_M3AP_MCEConfigurationUpdateFailure,	
	/* From module M3AP-IEs in ../support/r14.1.0/36444-e10.asn */
	&asn_DEF_M3AP_Absolute_Time_ofMBMS_Data,	
	&asn_DEF_M3AP_AllocationAndRetentionPriority,	
	&asn_DEF_M3AP_BitRate,	
	&asn_DEF_M3AP_Cause,	
	&asn_DEF_M3AP_CauseMisc,	
	&asn_DEF_M3AP_CauseNAS,	
	&asn_DEF_M3AP_CauseProtocol,	
	&asn_DEF_M3AP_CauseRadioNetwork,	
	&asn_DEF_M3AP_CauseTransport,	
	&asn_DEF_M3AP_CriticalityDiagnostics,	
	&asn_DEF_M3AP_CriticalityDiagnostics_IE_List,	
	&asn_DEF_M3AP_ECGI,	
	&asn_DEF_M3AP_EUTRANCellIdentifier,	
	&asn_DEF_M3AP_ExtendedMCE_ID,	
	&asn_DEF_M3AP_Global_MCE_ID,	
	&asn_DEF_M3AP_GBR_QosInformation,	
	&asn_DEF_M3AP_GTP_TEID,	
	&asn_DEF_M3AP_IPAddress,	
	&asn_DEF_M3AP_MBMS_Cell_List,	
	&asn_DEF_M3AP_MBMS_E_RAB_QoS_Parameters,	
	&asn_DEF_M3AP_MBMS_Service_associatedLogicalM3_ConnectionItem,	
	&asn_DEF_M3AP_MBMSServiceArea1,	
	&asn_DEF_M3AP_MBMS_Service_Area,	
	&asn_DEF_M3AP_MBMS_Session_Duration,	
	&asn_DEF_M3AP_MBMS_Session_ID,	
	&asn_DEF_M3AP_MCE_MBMS_M3AP_ID,	
	&asn_DEF_M3AP_MCE_ID,	
	&asn_DEF_M3AP_MCEname,	
	&asn_DEF_M3AP_MinimumTimeToMBMSDataTransfer,	
	&asn_DEF_M3AP_MME_MBMS_M3AP_ID,	
	&asn_DEF_M3AP_Pre_emptionCapability,	
	&asn_DEF_M3AP_Pre_emptionVulnerability,	
	&asn_DEF_M3AP_PriorityLevel,	
	&asn_DEF_M3AP_PLMN_Identity,	
	&asn_DEF_M3AP_QCI,	
	&asn_DEF_M3AP_Reestablishment,	
	&asn_DEF_M3AP_TimeToWait,	
	&asn_DEF_M3AP_TMGI,	
	&asn_DEF_M3AP_TNL_Information,	
	&asn_DEF_M3AP_TypeOfError,	
	/* From module M3AP-CommonDataTypes in ../support/r14.1.0/36444-e10.asn */
	&asn_DEF_M3AP_Criticality,	
	&asn_DEF_M3AP_Presence,	
	&asn_DEF_M3AP_PrivateIE_ID,	
	&asn_DEF_M3AP_ProcedureCode,	
	&asn_DEF_M3AP_ProtocolIE_ID,	
	&asn_DEF_M3AP_TriggeringMessage,	
	0
};

